chore!: Flatten upload options object
lukso-network/tools-lsp-factory pull request #105
Opened 2022-05-09 11:14 UTC by CallumGrindle

### What kind of change does this PR introduce (bug fix, feature, docs update, ...)?
Changes `uploadOptions` parameters to just `ipfsClientOptions`

2022-05-10 07:53 UTC, Hugoo approved these changes
cool - do you also need to update the docs to explain this new param?

2022-05-10 07:59 UTC, frozeman commented
Can you please describe in the PR description what you changed how? i want o prevent more rounds of back and forth.

As it looks like you simple changed the name from `uploadOptions` to `ipfsClientOptions`, but thats not what we agreed on.

Can you please show what the `ipfsClientOptions` look like?

It should be simply `ipfsGateway` with a string as value.
Ideally it also accepts an object as value with `url, port` and potentially others.

This way its flexible and extensible without breaking the API.

2022-05-10 11:59 UTC, frozeman commented
Lets please rename it to `ipfsGateway` to be consistent with erc725.js and allow both the object and a URL string to be passed in.

You can derive the port from the URL or present, otherwise use the standard port `5001`

2022-05-10 11:59 UTC, frozeman requested changes
see comment above

2022-05-10 11:59 UTC, frozeman commented
Ps. i dont understand the timeouts in the tests, are we not mocking transaction calls?

2022-05-10 17:59 UTC, CallumGrindle commented
@frozeman I have updated PR with changes. 

We use hardhat for transactions. I had problems with the tests due to IPFS issues so increased timeouts. They are unnecessary now so I have reverted

2022-05-16 12:27 UTC, merged

2022-05-16 16:47 UTC, CJ42 reviewed
added suggestion comments

2022-05-16 16:47 UTC, CJ42 commented on docs/deployment/digital-asset.md
> +You can specify how you want your profile metadata to be uploaded by passing the `ipfsGateway` inside the `options` object. Here you can set the IPFS gateway where you want the metadata to be uploade
**Suggested change:**

You can specify the IPFS network where you want to upload your profile metadata using an `ipfsGateway` object inside the `options` parameter.

2022-05-16 16:47 UTC, CJ42 commented on docs/deployment/digital-asset.md
> +The procedure takes a URL string or an object as defined by the [IPFS-HTTP Client](https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-http-client#createoptions) library which is used internall
Suggested change:

`procedure` -> `ipfsGateway` option

2022-05-16 16:47 UTC, CJ42 commented on docs/getting-started.md
> +When instantiating LSPFactory options can be passed to specify parameters such as `chainId` and `ipfsGateway`.
Suggested change:

_"The following parameters are available when creating an instance of the LSPFactory"_

2022-05-16 16:47 UTC, CJ42 commented on docs/getting-started.md
> +#### Deploy Key
Maybe a small table could be useful as a summary of the available options?

Like here: https://github.com/cgewecke/eth-gas-reporter#options